title: " "
logo: /assets/img/15000036_688518244648584_1662263079918462679_o.png
description: Hallmar Gauti Halldórsson,            Electronics engineer and musician
google_analytics:
theme: jekyll-theme-minimal
