plugins:
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain
title: Hallmar Gauti Halldórsson's Github website
author_name:        "Hallmar Gauti Halldórsson"
logo_url: https://avatars0.githubusercontent.com/u/38192440?v=4
