# Site Info
title:              "Hallmar's Projects"
description:        "A minimalist Jekyll theme"
author_name:        "Hallmar Gauti Halldórsson" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/u/38192440?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://hallmar.github.io # main url
baseurl:            /hallmar
permalink:          /:title # Post permalink
timezone:           Iceland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
