plugins:
  - jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
title: "My projects"
author_name:        "Hallmar Gauti Halldórsson"
logo_url: https://avatars0.githubusercontent.com/u/38192440?v=4

timezone:           Iceland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed
